/* ESTUDIO DE STG_ORDERS_CRM */
USE STAGE;

SELECT
    COUNT(*) TOTAL_REGISTROS,

    SUM(CASE LENGTH(TRIM(ID)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_ID,
    COUNT(DISTINCT CASE LENGTH(TRIM(ID)) WHEN 0 THEN 0 ELSE ID END) TOTAL_DISTINTOS_ID,

    SUM(CASE LENGTH(TRIM(ORD.ORDER)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_ORDER,
    COUNT(DISTINCT CASE LENGTH(TRIM(ORD.ORDER)) WHEN 0 THEN 0 ELSE ORD.ORDER END) TOTAL_DISTINTOS_ORDER,

    SUM(CASE LENGTH(TRIM(PHASE)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_PHASE,
    COUNT(DISTINCT CASE LENGTH(TRIM(PHASE)) WHEN 0 THEN 0 ELSE PHASE END) TOTAL_DISTINTOS_PHASE,

    SUM(CASE LENGTH(TRIM(AGENT)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_AGENT,
    COUNT(DISTINCT CASE LENGTH(TRIM(AGENT)) WHEN 0 THEN 0 ELSE AGENT END) TOTAL_DISTINTOS_AGENT,

    SUM(CASE LENGTH(TRIM(START_DT)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_START_DT,
    COUNT(DISTINCT CASE LENGTH(TRIM(START_DT)) WHEN 0 THEN 0 ELSE START_DT END) TOTAL_DISTINTOS_START_DT,

    SUM(CASE LENGTH(TRIM(END_DT)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_END_DT,
    COUNT(DISTINCT CASE LENGTH(TRIM(END_DT)) WHEN 0 THEN 0 ELSE END_DT END) TOTAL_DISTINTOS_END_DT

FROM STAGE.STG_ORDERS_CRM ORD;
