/* ESTUDIO DE STG_CONTACTOS_IVR */
USE STAGE;

SELECT
    COUNT(*) TOTAL_REGISTROS,

    SUM(CASE LENGTH(TRIM(ID)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_ID,
    COUNT(DISTINCT CASE LENGTH(TRIM(ID)) WHEN 0 THEN 0 ELSE ID END) TOTAL_DISTINTOS_ID,

    SUM(CASE LENGTH(TRIM(PHONE_NUMBER)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_PHONE_NUMBER,
    COUNT(DISTINCT CASE LENGTH(TRIM(PHONE_NUMBER)) WHEN 0 THEN 0 ELSE PHONE_NUMBER END) TOTAL_DISTINTOS_PHONE_NUMBER,

    SUM(CASE LENGTH(TRIM(START_DATETIME)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_START_DATETIME,
    COUNT(DISTINCT CASE LENGTH(TRIM(START_DATETIME)) WHEN 0 THEN 0 ELSE START_DATETIME END) TOTAL_DISTINTOS_START_DATETIME,

    SUM(CASE LENGTH(TRIM(END_DATETIME)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_END_DATETIME,
    COUNT(DISTINCT CASE LENGTH(TRIM(END_DATETIME)) WHEN 0 THEN 0 ELSE END_DATETIME END) TOTAL_DISTINTOS_END_DATETIME,

    SUM(CASE LENGTH(TRIM(SERVICE)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_SERVICE,
    COUNT(DISTINCT CASE LENGTH(TRIM(SERVICE)) WHEN 0 THEN 0 ELSE SERVICE END) TOTAL_DISTINTOS_SERVICE,

    SUM(CASE LENGTH(TRIM(FLG_TRANSFER)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_FLG_TRANSFER,
    COUNT(DISTINCT CASE LENGTH(TRIM(FLG_TRANSFER)) WHEN 0 THEN 0 ELSE FLG_TRANSFER END) TOTAL_DISTINTOS_FLG_TRANSFER,

    SUM(CASE LENGTH(TRIM(AGENT)) WHEN 0 THEN 0 ELSE 1 END) TOTAL_AGENT,
    COUNT(DISTINCT CASE LENGTH(TRIM(AGENT)) WHEN 0 THEN 0 ELSE AGENT END) TOTAL_DISTINTOS_AGENT

FROM STAGE.STG_CONTACTOS_IVR;
