/* FK PROVISION */
USE ODS;

ALTER TABLE ODS_HC_PROVISIONES ADD INDEX fk_pro_ser_idx (ID_SERVICIO ASC);
ALTER TABLE ODS_HC_PROVISIONES ADD CONSTRAINT fk_pro_ser FOREIGN KEY (ID_SERVICIO) REFERENCES ODS_HC_SERVICIOS (ID_SERVICIO);

ALTER TABLE ODS_HC_PROVISIONES ADD INDEX fk_pro_fas_idx (ID_FASE ASC);
ALTER TABLE ODS_HC_PROVISIONES ADD CONSTRAINT fk_pro_fas FOREIGN KEY (ID_FASE) REFERENCES ODS_DM_FASES (ID_FASE);

ALTER TABLE ODS_HC_PROVISIONES ADD INDEX fk_pro_age_idx (ID_AGENTE_PRV ASC);
ALTER TABLE ODS_HC_PROVISIONES ADD CONSTRAINT fk_pro_age FOREIGN KEY (ID_AGENTE_PRV) REFERENCES ODS_DM_AGENTES_PRV (ID_AGENTE_PRV);
