/* FK SERVICIOS */
USE ODS;

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_cli FOREIGN KEY (ID_CLIENTE) REFERENCES ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_pro_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_pro FOREIGN KEY (ID_PRODUCTO) REFERENCES ODS_DM_PRODUCTOS (ID_PRODUCTO);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_can_idx (ID_CANAL ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_can FOREIGN KEY (ID_CANAL) REFERENCES ODS_DM_CANALES (ID_CANAL);

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_ser_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_dir FOREIGN KEY (ID_DIRECCION_SERVICIO) REFERENCES ODS_HC_DIRECCIONES (ID_DIRECCION);
