/* TABLAS SERVICIOS */
USE ODS;

DROP TABLE IF EXISTS ODS_HC_SERVICIOS;

CREATE TABLE ODS_HC_SERVICIOS (
    ID_SERVICIO INT UNSIGNED NOT NULL PRIMARY KEY,
    ID_CLIENTE INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    PUNTO_ACCESO VARCHAR(512),
    ID_CANAL INT UNSIGNED,
    ID_AGENTE INT UNSIGNED,
    ID_DIRECCION_SERVICIO INT UNSIGNED,
    FC_INICIO DATETIME,
    FC_INSTALACION DATETIME,
    FC_FIN DATETIME,
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_PRODUCTOS;

CREATE TABLE ODS_DM_PRODUCTOS (
    ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DE_PRODUCTO VARCHAR(512),
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_CANALES;

CREATE TABLE ODS_DM_CANALES (
    ID_CANAL INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DE_CANAL VARCHAR(512),
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);
