/* TABLAS PROVISION */
USE ODS;

DROP TABLE IF EXISTS ODS_HC_PROVISIONES;

CREATE TABLE ODS_HC_PROVISIONES (
    ID_PROVISION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_ORDER INT UNSIGNED,
    ID_SERVICIO INT UNSIGNED,
    ID_FASE INT UNSIGNED,
    ID_AGENTE_PRV INT UNSIGNED,
    FC_INICIO DATETIME,
    FC_FIN DATETIME,
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_FASES;

CREATE TABLE ODS_DM_FASES (
    ID_FASE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DE_FASE VARCHAR(512),
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_AGENTES_PRV;

CREATE TABLE ODS_DM_AGENTES_PRV (
    ID_AGENTE_PRV INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DE_AGENTE_PRV VARCHAR(512),
    FC_INSERT DATETIME,
    FC_MODIFICATION DATETIME
);
