/* POBLAR SERVICIOS */
USE ODS;

INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)) AS CANAL, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(CHANNEL))<>0
ORDER BY CANAL;

INSERT INTO ODS_DM_CANALES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_CANALES;


INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)) AS PRODUCTO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(PRODUCT_NAME))<>0
ORDER BY PRODUCTO;

INSERT INTO ODS_DM_PRODUCTOS VALUES (99, 'DESCONOCIDO', NOW(),NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (98, 'NO APLICA', NOW(),NOW());

COMMIT;

ANALYZE TABLE ODS_DM_PRODUCTOS;


INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_COUNTRY)) AS PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
LEFT OUTER JOIN ODS_DM_PAISES PAI ON
    CASE WHEN LENGTH(TRIM(PRODUCT_COUNTRY))<>0 THEN REPLACE(PRODUCT_COUNTRY, 'United States', 'US') ELSE 'DESCONOCIDO' END = PAI.DE_PAIS
WHERE LENGTH(TRIM(PRODUCT_COUNTRY))<>0
AND PAI.ID_PAIS IS NULL
ORDER BY PAIS;

COMMIT;

ANALYZE TABLE ODS_DM_PAISES;


INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT CASE WHEN TRIM(PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END CIUDAD,
CASE WHEN TRIM(PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END ESTADO,
PAI.ID_PAIS, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS_DM_PAISES PAI ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN REPLACE(PRO.PRODUCT_COUNTRY, 'United States', 'US') ELSE 'DESCONOCIDO' END=PAI.DE_PAIS
LEFT OUTER JOIN ODS_DM_CIUDADES_ESTADOS CIU ON 
    CASE WHEN TRIM(PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END = CIU.DE_CIUDAD
    AND CASE WHEN TRIM(PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END = CIU.DE_ESTADO
    AND PAI.ID_PAIS = CIU.ID_PAIS
WHERE (TRIM(PRODUCT_CITY)<>'' OR TRIM(PRODUCT_STATE)<>'')
AND CIU.ID_CIUDAD_ESTADO IS NULL;

COMMIT;

ANALYZE TABLE ODS_DM_CIUDADES_ESTADOS;


INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(PRODUCT_ADDRESS)) DIRECCION,
CASE WHEN LENGTH(TRIM(PRO.PRODUCT_POSTAL_CODE))<>0 THEN TRIM(PRO.PRODUCT_POSTAL_CODE) ELSE 99999 END CP,
CIU.ID_CIUDAD_ESTADO, NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS_DM_PAISES PAI ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN REPLACE(PRO.PRODUCT_COUNTRY, 'United States', 'US') ELSE 'DESCONOCIDO' END=PAI.DE_PAIS
INNER JOIN ODS_DM_CIUDADES_ESTADOS CIU ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN PRO.PRODUCT_CITY ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
                                          AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN PRO.PRODUCT_STATE ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
LEFT OUTER JOIN ODS_HC_DIRECCIONES DIR ON 
    CASE WHEN TRIM(PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END = DIR.DE_DIRECCION
    AND CASE WHEN TRIM(PRODUCT_POSTAL_CODE)<>'' THEN UPPER(TRIM(PRODUCT_POSTAL_CODE)) ELSE 'DESCONOCIDO' END = DIR.DE_CP
    AND CIU.ID_CIUDAD_ESTADO = DIR.ID_CIUDAD_ESTADO
WHERE TRIM(PRODUCT_ADDRESS)<>''
AND DIR.ID_CIUDAD_ESTADO IS NULL;

COMMIT;

ANALYZE TABLE ODS_HC_DIRECCIONES;


INSERT INTO ODS_HC_CLIENTES
SELECT DISTINCT UPPER(TRIM(CUSTOMER_ID)) ID_CLIENTE,
'DESCONOCIDO', 'DESCONOCIDO', '99-999-9999', 99, 999999, 9999999999, 'DESCONOCIDO', STR_TO_DATE('31/12/9999', '%d/%m/%Y'), 999, 999, NOW(), STR_TO_DATE('31/12/9999', '%d/%m/%Y')
FROM STAGE.STG_PRODUCTOS_CRM PRO
LEFT OUTER JOIN ODS_HC_CLIENTES CLI ON 
    CASE WHEN TRIM(CUSTOMER_ID)<>'' THEN UPPER(TRIM(CUSTOMER_ID)) ELSE 'DESCONOCIDO' END = CLI.ID_CLIENTE
WHERE TRIM(PRODUCT_ADDRESS)<>''
AND CLI.ID_CLIENTE IS NULL;

COMMIT;

ANALYZE TABLE ODS_HC_CLIENTES;


INSERT INTO ODS_HC_SERVICIOS
SELECT
    PRODUCT_ID AS ID_SERVICIO,
    CLI.ID_CLIENTE,
    PRO.ID_PRODUCTO,
    ACCESS_POINT AS PUNTO_ACCESO,
    CAN.ID_CANAL,
    CASE WHEN LENGTH(TRIM(AGENT_CODE))<>0 THEN TRIM(AGENT_CODE) ELSE 9998 END ID_AGENTE,
    CASE WHEN LENGTH(TRIM(DIR.ID_DIRECCION))<>0 THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION,
    CASE WHEN LENGTH(TRIM(START_DATE))<>0 THEN STR_TO_DATE(START_DATE, '%d/%m/%Y') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO,
    CASE WHEN LENGTH(TRIM(INSTALL_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(INSTALL_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9998', '%d/%m/%Y') END FC_INSTALACION,
    CASE WHEN LENGTH(TRIM(END_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(END_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9998', '%d/%m/%Y') END FC_FIN,
    NOW(),
    STR_TO_DATE('31/12/9999', '%d/%m/%Y')

FROM
    STAGE.STG_PRODUCTOS_CRM PRODUCTOS

INNER JOIN 
	ODS_DM_PRODUCTOS PRO ON CASE WHEN LENGTH(TRIM(PRODUCT_NAME))<>0 THEN UPPER(TRIM(PRODUCTOS.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END=PRO.DE_PRODUCTO
INNER JOIN 
	ODS_DM_CANALES CAN ON CASE WHEN LENGTH(TRIM(CHANNEL))<>0 THEN UPPER(TRIM(PRODUCTOS.CHANNEL)) ELSE 'DESCONOCIDO' END=CAN.DE_CANAL
LEFT OUTER JOIN
	ODS_HC_CLIENTES CLI ON CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>0 THEN TRIM(CUSTOMER_ID) ELSE 999999999 END=CLI.ID_CLIENTE
LEFT OUTER JOIN (
	ODS_HC_DIRECCIONES DIR INNER JOIN ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO=CIU.ID_CIUDAD_ESTADO
	INNER JOIN ODS_DM_PAISES PAI ON CIU.ID_PAIS=PAI.ID_PAIS
) ON 
	CASE WHEN TRIM(PRODUCT_ADDRESS)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
	AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_POSTAL_CODE)) ELSE 99999 END=DIR.DE_CP
	AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_CITY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=CIU.DE_CIUDAD
	AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_STATE)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END=CIU.DE_ESTADO
	AND CASE WHEN TRIM(PRODUCTOS.PRODUCT_COUNTRY)<>'' THEN UPPER(TRIM(PRODUCTOS.PRODUCT_COUNTRY)) ELSE 'DESCONOCIDO' END=PAI.DE_PAIS;

COMMIT;

ANALYZE TABLE ODS_HC_SERVICIOS;
