/* POBLAR LLAMADAS */
USE ODS;

INSERT INTO ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(SERVICE)) AS DEPARTAMENTO_CC, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE LENGTH(TRIM(SERVICE))<>0
ORDER BY DEPARTAMENTO_CC;

INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_DEPARTAMENTOS_CC;


INSERT INTO ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(AGENT)) AS AGENTE_CC, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE LENGTH(TRIM(AGENT))<>0
ORDER BY AGENTE_CC;

INSERT INTO ODS_DM_AGENTES_CC VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES_CC VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_AGENTES_CC;


INSERT INTO ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA, ID_CLIENTE, FC_INICIO_LLAMADA, FC_FIN_LLAMADA, ID_DEPARTAMENTO_CC, FLG_TRANSFERIDO, ID_AGENTE_CC, FC_INSERT, FC_MODIFICATION)
SELECT
    ID AS ID_IVR,
    CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>0 THEN TRIM(PHONE_NUMBER) ELSE 9999999999 END TELEFONO_LLAMADA,
    CASE WHEN LENGTH(TRIM(CLI.ID_CLIENTE))<>0 THEN TRIM(CLI.ID_CLIENTE) ELSE 999999999 END ID_CLIENTE,
    CASE WHEN LENGTH(TRIM(START_DATETIME))<>0 THEN STR_TO_DATE(SUBSTRING(START_DATETIME, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO_LLAMADA,
    CASE WHEN LENGTH(TRIM(END_DATETIME))<>0 THEN STR_TO_DATE(SUBSTRING(END_DATETIME, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN_LLAMADA,
    DEP_CC.ID_DEPARTAMENTO_CC AS ID_DEPARTAMENTO_CC,
    CASE UPPER(TRIM(FLG_TRANSFER)) WHEN 'TRUE' THEN 1 ELSE 0 END FLG_TRANSFERIDO,
    AGE_CC.ID_AGENTE_CC AS ID_AGENTE_CC,
    NOW(),
    STR_TO_DATE('31/12/9999', '%d/%m/%Y')

FROM
    STAGE.STG_CONTACTOS_IVR CONTACTOS

INNER JOIN 
	ODS_DM_DEPARTAMENTOS_CC DEP_CC ON CASE WHEN LENGTH(TRIM(SERVICE))<>0 THEN UPPER(TRIM(CONTACTOS.SERVICE)) ELSE 'DESCONOCIDO' END=DEP_CC.DE_DEPARTAMENTO_CC
INNER JOIN 
	ODS_DM_AGENTES_CC AGE_CC ON CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN UPPER(TRIM(CONTACTOS.AGENT)) ELSE 'DESCONOCIDO' END=AGE_CC.DE_AGENTE_CC
LEFT OUTER JOIN
	ODS_HC_CLIENTES CLI ON CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>0 THEN TRIM(PHONE_NUMBER) ELSE 999999999 END=CLI.TELEFONO_CLIENTE;

COMMIT;

ANALYZE TABLE ODS_HC_LLAMADAS;
