/* POBLAR FACTURAS */
USE ODS;

INSERT INTO ODS_DM_CICLOS_FACTURACION (DE_CICLO_FACTURACION, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(BILL_CYCLE)) AS CICLO_FACTURACION, NOW(), NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE LENGTH(TRIM(BILL_CYCLE))<>0
ORDER BY CICLO_FACTURACION;

INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_CICLOS_FACTURACION;


INSERT INTO ODS_DM_METODOS_PAGO (DE_METODO_PAGO, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(BILL_METHOD)) AS METODO_PAGO, NOW(), NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE LENGTH(TRIM(BILL_METHOD))<>0
ORDER BY METODO_PAGO;

INSERT INTO ODS_DM_METODOS_PAGO VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_METODOS_PAGO VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_METODOS_PAGO;

INSERT INTO ODS_HC_CLIENTES VALUES (999999999,'DESCONOCIDO', 'DESCONOCIDO','99-999-9999', 99, 999999, 9999999999, 'DESCONOCIDO', STR_TO_DATE('31/12/9999', '%d/%m/%Y'), 999, 999, NOW(), STR_TO_DATE('31/12/9999', '%d/%m/%Y'));

COMMIT;

ANALYZE TABLE ODS_HC_CLIENTES;



INSERT INTO ODS_HC_FACTURAS
SELECT
    BILL_REF_NO AS ID_FACTURA,
    CASE WHEN LENGTH(TRIM(CLI.ID_CLIENTE))<>0 THEN TRIM(CLI.ID_CLIENTE) ELSE 999999999 END ID_CLIENTE,
    CASE WHEN LENGTH(TRIM(START_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(START_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO,
    CASE WHEN LENGTH(TRIM(END_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(END_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN,
    CASE WHEN LENGTH(TRIM(STATEMENT_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(STATEMENT_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_ESTADO,
    CASE WHEN LENGTH(TRIM(PAYMENT_DATE))<>0 THEN STR_TO_DATE(SUBSTRING(PAYMENT_DATE, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_PAGO,
    CI_FA.ID_CICLO_FACTURACION,
    ME_PA.ID_METODO_PAGO,
    CASE WHEN LENGTH(TRIM(AMOUNT))<>0 THEN CAST(AMOUNT AS DECIMAL(5,2)) ELSE '99999.99' END CANTIDAD,
    NOW(),
    STR_TO_DATE('31/12/9999', '%d/%m/%Y')

FROM
    STAGE.STG_FACTURAS_FCT FACTURAS

INNER JOIN 
	ODS_DM_CICLOS_FACTURACION CI_FA ON CASE WHEN LENGTH(TRIM(BILL_CYCLE))<>0 THEN UPPER(TRIM(FACTURAS.BILL_CYCLE)) ELSE 'DESCONOCIDO' END=CI_FA.DE_CICLO_FACTURACION
INNER JOIN 
	ODS_DM_METODOS_PAGO ME_PA ON CASE WHEN LENGTH(TRIM(BILL_METHOD))<>0 THEN UPPER(TRIM(FACTURAS.BILL_METHOD)) ELSE 'DESCONOCIDO' END=ME_PA.DE_METODO_PAGO
LEFT OUTER JOIN
	ODS_HC_CLIENTES CLI ON CASE WHEN LENGTH(TRIM(CUSTOMER_ID))<>0 THEN TRIM(CUSTOMER_ID) ELSE 999999999 END=CLI.ID_CLIENTE;

COMMIT;

ANALYZE TABLE ODS_HC_FACTURAS;
