/* POBLAR PROVISION */
USE ODS;

INSERT INTO ODS_DM_FASES (DE_FASE, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(PHASE)) AS FASE, NOW(), NOW()
FROM STAGE.STG_ORDERS_CRM
WHERE LENGTH(TRIM(PHASE))<>0
ORDER BY FASE;

INSERT INTO ODS_DM_FASES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_FASES VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_FASES;


INSERT INTO ODS_DM_AGENTES_PRV (DE_AGENTE_PRV, FC_INSERT, FC_MODIFICATION)
SELECT DISTINCT UPPER(TRIM(AGENT)) AS AGENTE_PRV, NOW(), NOW()
FROM STAGE.STG_ORDERS_CRM
WHERE LENGTH(TRIM(AGENT))<>0
ORDER BY AGENTE_PRV;

INSERT INTO ODS_DM_AGENTES_PRV VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES_PRV VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_AGENTES_PRV;


INSERT INTO ODS_HC_PROVISIONES (ID_ORDER, ID_SERVICIO, ID_FASE, ID_AGENTE_PRV, FC_INICIO, FC_FIN, FC_INSERT, FC_MODIFICATION)
SELECT
    ID AS ID_ORDER,
    SER.ID_SERVICIO AS ID_SERVICIO,
    FAS.ID_FASE AS ID_FASE,
    AGE_PRV.ID_AGENTE_PRV AS ID_AGENTE_PRV,
    CASE WHEN LENGTH(TRIM(START_DT))<>0 THEN STR_TO_DATE(SUBSTRING(START_DT, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO,
    CASE WHEN LENGTH(TRIM(END_DT))<>0 THEN STR_TO_DATE(SUBSTRING(END_DT, 1, 19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN,
    NOW(),
    STR_TO_DATE('31/12/9999', '%d/%m/%Y')

FROM
    STAGE.STG_ORDERS_CRM ORDERS

INNER JOIN 
	ODS_DM_FASES FAS ON CASE WHEN LENGTH(TRIM(PHASE))<>0 THEN UPPER(TRIM(ORDERS.PHASE)) ELSE 'DESCONOCIDO' END=FAS.DE_FASE
INNER JOIN 
	ODS_DM_AGENTES_PRV AGE_PRV ON CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN UPPER(TRIM(ORDERS.AGENT)) ELSE 'DESCONOCIDO' END=AGE_PRV.DE_AGENTE_PRV
LEFT OUTER JOIN
	ODS_HC_SERVICIOS SER ON CASE WHEN LENGTH(TRIM(ORDERS.ORDER))<>0 THEN TRIM(ORDERS.ORDER) ELSE 999999999 END=SER.ID_SERVICIO;

COMMIT;

ANALYZE TABLE ODS_HC_PROVISIONES;
